# Generated by Django 2.1.5 on 2019-01-22 16:19

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]*$', message='допустимы только буквенные символы.')], verbose_name='логин для входа в систему')),
                ('nickname', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', message='только буквенноцифровые символы допустимы.')], verbose_name='имя пользователя в системе')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='электронная почта')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='фамилия пользователя')),
                ('tagline', models.CharField(blank=True, max_length=140, null=True, verbose_name='статус')),
                ('photo', models.FilePathField(blank=True, default='defaultprofileimage.jpg', null=True, verbose_name='аватар')),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='укажите правильный номер телефона', regex='^\\d{10}$')], verbose_name='сотовый телефон')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='последнее обновление')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
