# Generated by Django 2.1.5 on 2019-01-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190129_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='pseudonym',
        ),
    ]
