# Generated by Django 2.1.5 on 2019-01-22 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterpart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование компании')),
                ('boss_first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='имя руководителя')),
                ('boss_second_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='отчество руководителя')),
                ('boss_last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='фамилия руководителя')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='укажите правильный номер телефона', regex='^\\d{10}$')], verbose_name='контактный телефон')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='ОГРН')),
                ('okpo', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='ОКПО')),
                ('okato', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='ОКАТО')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес организации')),
                ('account', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='банковский счёт')),
                ('bik', models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='БИК')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterpart', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'db_table': 'counterparties',
            },
        ),
        migrations.CreateModel(
            name='CounterpartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Физическое лицо', 'Физическое лицо'), ('Коммерческая организация', 'Коммерческая организация'), ('Банк', 'Банк'), ('Центральный Банк', 'Центральный банк'), ('Государственное учреждение', 'Государственная учреждение')], default='Физическое лицо', max_length=100, unique=True, verbose_name='вид контрагента')),
            ],
            options={
                'verbose_name': 'вид контрагента',
                'verbose_name_plural': 'виды контрагентов',
                'db_table': 'counterpart_type',
            },
        ),
        migrations.AddField(
            model_name='counterpart',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.CounterpartType', verbose_name='вид контрагента'),
        ),
    ]
