# Generated by Django 2.1.5 on 2019-01-22 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_counterpart_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpart',
            name='employees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='сотрудники'),
        ),
        migrations.AlterField(
            model_name='counterpart',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{11}$')], verbose_name='контактный телефон'),
        ),
    ]
